name: Linting
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout Super-Linter
      - uses: actions/checkout@v2

      # run Linter
      - name: Super-Linter
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_NATURAL_LANGUAGE: false
          
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
