name: Linting 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current branch
        id: extract_branch
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"


      # checkout Super-Linter
      - uses: actions/checkout@v2
      
      # run Linter
      - name: Super-Linter
        uses: docker://github/super-linter:latest
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
