name: Linting 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: myref

      # checkout Super-Linter
      - uses: actions/checkout@v2
      
      # run Linter
      - name: Super-Linter
        uses: docker://github/super-linter:latest
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: $GITHUB_REF
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
